# Generated by Django 4.0.4 on 2022-05-23 03:51

from django.db import migrations, models
import pbl5_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pbl5_api.models.nameFile)),
            ],
        ),
    ]
