# Generated by Django 4.0.4 on 2022-06-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbl5_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimagetest',
            name='createAt',
            field=models.DateTimeField(null=True),
        ),
    ]
