# Generated by Django 4.0.4 on 2022-06-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbl5_api', '0002_uploadimagetest_createat'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimagetest',
            name='disease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadimagetest',
            name='overview',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='uploadimagetest',
            name='plantName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadimagetest',
            name='predictAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='uploadimagetest',
            name='solutions',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
