# Generated by Django 4.0.4 on 2022-06-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbl5_api', '0004_uploadimagetest_imagesimiler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimagetest',
            old_name='imageSimiler',
            new_name='imageSimilar',
        ),
    ]
